#!/usr/bin/env bash
# Transfer file from client to server

file=$1 
ip=$2
user=$3
pkey=$4

if [ $# -ne 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i "$pkey" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/
