#!/usr/bin/env bash
#Install NGINX and configue the default html page

apt-get -y update
apt-get -y install nginx
service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/h404.html
newlines="\\\terror_page 404 /h404.html;\n\tlocation = /h404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n\t}"
sed -i "27i $newlines" /etc/nginx/sites-available/default
service nginx restart
service nginx reload
