#!/usr/bin/env bash
# This script prints Best School 10 times at 9th prints it with hi
n=1
while [ $n -le 10 ]
do
    if [ $n -gt 9 ];
    then
        echo "Hi"
    fi
    echo "Best School"
    n=$(( n+1 ))
done
