#!/usr/bin/env bash
# This script prints Best School 10 times and ...
n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 4 ];
    then
        echo "bad luck"
   
    elif  [ $n -eq 8 ]
    then
        echo "good luck"
    fi
    n=$(( n+1 ))
done
