#!/usr/bin/env bash
# This script prints Best School 10 times and ...
n=1
while [ $n -le 9 ]
do
    if [ $n == 3 ];
    then
        echo "bad luck"
   
    elif  [ $n -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    n=$(( n+1 ))
done
