#!/usr/bin/env bash
# This script that gives you information about the school file.
# -e FILE - True if the FILE exists and is a file, regardless of type (node, directory)
# -s FILE - True if the FILE exists and has nonzero size
FILE="school"
if [ -e "$FILE" ] 
then
    echo "school file exists."
    if [ -s "$FILE" ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "tonschool is a regular file"
    fi
else
    echo "school file does not exist"

fi
