#!/usr/bin/env bash
# This script that gives you information about the school file.
# -e FILE - True if the FILE exists and is a file, regardless of type (node, directory)
# -s FILE - True if the FILE exists and has nonzero size
FILE=school
if test -e "$FILE"  
then
    echo "$FILE file exists."
    if test -s "$FILE"
    then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi
    if  text -f "$FILE" 
    then
        echo "$FILE is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
